services/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'services'
urlpatterns = [
    path('services/', views.testing_service_list, name='services'),
    path('service_form/', views.create_service_testing, name= 'service_form'),
    path('serviceform/', views.create_service_testing1, name='serviceform'),
    path('services/service-detail/<int:id>', views.service_detail, name='service-detail'),
    path('services/search/', views.search_services, name='search'),
    path('', views.category, name='categories'),
    path('adding_categories', views.adding_categories, name='adding_categories'),
    path('categories/service_by_category/<int:id>/', views.services_by_categories, name='service_by_category'),
    path('services/update/<int:id>', views.update_service, name='update_service'),
    path('services/deleting/<int:id>', views.delete_service, name='delete_service'),
    path('categories/deleting_one_category/<int:id>', views.delete_category, name='deleting_one_category'),
    path('categories/deleting_all_categories/<int:id>', views.delete_all_categories, name='deleting_all_categories'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techfutuers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
app_name = 'services'
urlpatterns = [
    path("admin/", admin.site.urls),
    path('services', include(('services.urls', 'services'), namespace='services')),
    path('', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path('', views.register, name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('userprofile-details/<int:user__pk>/', views.UserProfileDetail.as_view(), name='userprofile-details'),
    path('profilepictures/<int:pk>/', views.ProfilePictureDetail.as_view(), name='profilepicture-detail'),
    path('profile/', views.profile_view, name='profile')
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/models.py
from django.db import models

# Create your models here.

class Categories(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    category_description = models.CharField(max_length=200, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return f"{self.name}"
#
# class User(models.Model):
#     name = models.CharField(max_length=100)
#     image = models.ImageField()

# class Subcategory(models.Model):
#     name = models.CharField(max_length=100)
#     category = models.ForeignKey(Categories, on_delete=models.CASCADE)
class Services(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE) # many_to_many relationship
    # subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, null=True, blank=True)
    # video_ulr = models.URLField(null=True, blank=True)
    # client = models.ManyToManyField(User, through='Booking') #

    def __str__(self):
        return f'{self.name}'

class ServiceImages(models.Model):
    service = models.ForeignKey(Services, on_delete=models.CASCADE)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to='media/service_images/')

# class Booking(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     service = models.ForeignKey(Services, on_delete=models.CASCADE)
#     booking_date = models.DateTimeField(auto_now_add=True)
#

# class Order(models.Model):
#     service = models.ForeignKey(Services, on_delete=models.CASCADE) # many_to_many relationship
#     # user = models.ForeignKey(User, on_delete=models.CASCADE)
#     quantity = models.PositiveIntegerField()
#     total_price = models.DecimalField(max_length=10, decimal_places=2)
#     order_date =models.DateTimeField(auto_now_add=True)

# class Reviews(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     service = models.ForeignKey(Services, on_delete=models.CASCADE)
#     rating = models.PositiveIntegerField(choices=[(i, i) for i in range(1, 6)])
#     comment = models.TextField()
#     review_date = models.DateTimeField(auto_now_add=True)

services/forms.py
from django import forms
from .models import Categories, Services, ServiceImages

class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = ['name', 'category_description']

class ServicesForms(forms.ModelForm):
    # category = forms.ModelChoiceField(queryset=Categories.objects.all())
    # subcategory = forms.ModelChoiceField(queryset=Subcategory.objects.all(), required=False)

    class Meta:
        model = Services
        fields = ['name', 'description', 'price', 'category'] #'subcategory']

class ServiceImageForm(forms.ModelForm):
    class Meta:
        model = ServiceImages
        fields = ['image']

class ServiceUpdateForm(forms.ModelForm):
    class Meta:
        model = Services
        fields = ['name', 'description', 'price', 'category',]

services/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.template import loader
from django.views.generic import CreateView
from django.forms import inlineformset_factory
from .forms import *
from django.http import JsonResponse
import cgi

from .models import Services, ServiceImages, Categories
from .forms import ServicesForms, ServiceImageForm, ServiceUpdateForm

# Create a formset factory for ServiceImageForm
ServiceImageFormSet = inlineformset_factory(Services, ServiceImages, form=ServiceImageForm, extra=3)


def adding_categories(request):
    template = loader.get_template('category_adding.html')
    if request.method == 'POST':
        form = CategoriesForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')  # categories list
    else:
        form = CategoriesForm()
    context = {
        'form': form,
    }
    return HttpResponse(template.render(context, request))


def testing_service_list(request):
    services = Services.objects.all()
    template = loader.get_template('testing_service.html')
    # print(services)
    context = {
        'services': services,
    }
    return HttpResponse(template.render(context, request))


def services_by_categories(request, id):
    category = get_object_or_404(Categories, id=id)
    services = Services.objects.filter(category=category)
    template = loader.get_template('service_by_category.html')
    context = {
        'category': category,
        'services': services,
    }
    return HttpResponse(template.render(context, request))


def service_detail(request, id):
    service = Services.objects.get(pk=id)
    images = ServiceImages.objects.filter(service=service)
    context = {
        'service': service,
        'images': images,
    }
    return render(request, 'service_details.html', context)


def create_service_testing1(request):
    template = loader.get_template('serviceform.html')
    if request.method == 'POST':
        form = ServicesForms(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('categories')
    else:
        form = ServicesForms()
    context = {
        'form': form,
    }
    return HttpResponse(template.render(context, request))


def category(request, ):  # view to list all
    categories = Categories.objects.all()  # Get all categories
    template = loader.get_template('category.html')

    context = {
        # 'category':category,
        'categories': categories,
    }

    return HttpResponse(template.render(context, request))


class ServiceCreateView(CreateView):
    model = Services
    form_class = ServicesForms
    template_name = 'service_form.html'
    success_url = '/'

    def form_valid(self, form):
        response = super().form_valid(form)
        # After the Service is create, associate images with it
        service = self.object
        image_formset = ServiceImageFormSet(self.request.POST, self.request.FILE, instance=service)
        if image_formset.is_valid():
            image_formset.save()
        return response


#     Function view equivalent
def create_service_testing(request):
    template_name = 'service_form.html'

    if request.method == 'POST':
        form = ServicesForms(request.POST)
        formset = ServiceImageFormSet(request.POST, request.FILES, instance=None)  # instance=None

        if form.is_valid() and formset.is_valid():
            service = form.save()  # Save the main service data
            instances = formset.save(commit=False)

            for instance in instances:
                instance.service = service
                instance.save()

            return redirect('services')  # Redirect ather successful form submission
    else:
        form = ServicesForms()
        formset = ServiceImageFormSet()
    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, template_name, context)



# def services_list(request):
#     services = Services.objects.all()
#     services_with_images = Services.objects.exclude(image__isnull=True)
#
#     categories = Catergory.objects.filter(parent_category__isnull = True)
def search_services(request, ):
    query = request.GET.get('q', '')
    # service = get_object_or_404(Services, pk=id)
    results = []
    if query:
        results = Services.objects.filter(Q(name__startswith=query) | Q(category__name__startswith=query) |
                                          Q(name__iendswith=query) | Q(category__name__iendswith=query))
    print(results)
    print(query)
    context = {
        'query': query,
        'results': results,
        # 'service':service,
    }
    return render(request, 'search.html', context)


def search_for_services(request):
    query = request.GET.get('q')  # Get the search query from the user
    # Perform filter based on the query
    results = Services.objects.filter(
        Q(name__icontains=query) |
        Q(category_name__name__icontains=query)
    )
    context = {
        'query': query,
        'results': results,
    }
    return render(request, 'testing_service.html', context)


def update_service(request, id):
    service = get_object_or_404(Services, id=id)  # retrieve the service
    # Check if the user has permissions to update this service
    # if not user_has_permission_to_update(request.user, service):
    # return  HttpResponseForbidden("You don't have permission to update this service.")

    if request.method == 'POST':
        form = ServiceUpdateForm(request.POST, request.FILES, instance=service)
        if form.is_valid():
            # Save the updated service details
            form.save()
            print(form)
            return redirect('service-detail', id=id)
        else:
            # Handle the update service details
            return redirect(request, 'update_service.html', {'form': form, 'service': service})
    else:
        form = ServiceUpdateForm(instance=service)

    return render(request, 'update_service.html', {'form': form, 'service': service})
    # return HttpResponse('This ia placeholder response if none of the conditions are met. ')

def delete_service(request, id):
    template = loader.get_template('delete.html')
    service = get_object_or_404(Services, id=id)
    # if not user_has_permission_to_update(request.user, service):
    #     return HttpResponseForbidden("You don't have permission to delete this service")

    if request.method == 'POST':
        if service.image:
            service.image.delete()  # deletes an image if it's associated with a service
        service.delete()
        return  HttpResponseRedirect('services')
    context ={
        'service':service,
    }
    return HttpResponse(template.render(context, request))

def delete_category(request, id):
    template = loader.get_template('delete.html')
    category = get_object_or_404(id=id)

    if request.method == 'POST':
        Services.objects.filter(category=category).delete()
        category.delete()
        return HttpResponseRedirect('categories')

    context = {
        'category':category,
    }
    return HttpResponse(template.render(context, request))


def delete_all_categories(request):
    template = loader.get_template('delete.html')

    if request.method == 'POST':
        categories = Categories.objects.all()
        for category in categories:
            Services.objects.filter(category=category)
            category.delete()
        return HttpResponseRedirect('categories')
    categories = Categories.objects.all()
    context = {
        'categories':categories,
    }
    return HttpResponse(template.render(context, request))

services/templates/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for x in categories %}
<a href="{% url 'services:service_by_category' x.id %}">
    <p>{{x.name}}</p>
</a>
{% endfor %}
</body>
</html>

services/templates/category_adding.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
  <button type="submit">Add A Category</button>
</form>
</body>
</html>

services/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
   <h1>Deleting services</h1>
   <p>Are you sure you want to delete {{service.name}}</p>
    <button type="submit">YES DELETE</button>
</form>

</body>
</html>

services/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
    <script src="http://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function(){
            var typingTimer;
            var doneTypingInterval = 500;
            $("#search-input").on("keyup", function(){
                clearTimeout(typingTimer);
                var query = $(this).val();
                if (query.length === 0){
                    $("#livesearch").empty();
                    return;
                }
                typingTimer = setTimeout(function(){
                    $.ajax({
                        url:"{% url 'search'  %}?q=" +query,
                        type: "GET",
                        success: function(data){
                            $("#livesearch").html(data);
                        }
                    });
             }, doneTypingInterval);
            });
        });
    </script>
</head>
<body>
    <form>
        <input type="text" id="search-input" size="30">
    </form>
    <div id="livesearch">
        {% if results %}
        <ul>
            {% for service in results %}
            <li><a href="{% url 'service-detail' service.id %}">{{service.name}}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p>No results found</p>
        {% endif %}
    </div>
</body>
</html>

services/templates/service_by_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for a in services %}
<a href="{% url 'services:service-detail' a.id %}"><p>{{a.name}}</p></a>
{% endfor %}
</body>
</html>

services/templates/service_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Details about {{service.name}} {%endblock %}</title>
</head>
<body>
<h2>{{service.name}}</h2>
<p>{{service.price}}</p>
<p>{{service.description}}</p>
{% for image in images %}
<img src="{{ image.image.url }}" alt="{{service.name}} image">
{% endfor %}
</body>
</html>

services/templates/service_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {{form.as_p}}
    {{ form.subcategory.label_tag}}
    {{form.subcategory}}
    {{formset.management_form}}

    {% for form in formset %}
    {{ form.as_table}}
    {% endfor %}
    <button type="submit">Create Service</button>
</form>
</body>
</html>

services/templates/serviceform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action="" >
    {%csrf_token%}
    {{form.as_p}}
    {% for form in formset %}
    {{form.as_p}}
    {% endfor %}
    <button type="submit">Create</button>
</form>
<a href="{% url 'services' %}">Back to Service List</a>
</body>
</html>

services/templates/testing_service.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Services offered By TechFutures: </h1>
<ul>
    {% for a in services %}
    <li><a href="{% url 'services:service-detail' a.id %}">{{a.name}} (ID: {{a.id}})</a></li>
    {% endfor %}
</ul>
{% for service in services %}
<h1>{{ service.name }}</h1>
<p> Price: {{service.price}}</p>
<p>Category: {{service.category.name}}</p>
<p>Description: {{service.description}}</p>
{%if service.subcategory %}
<p>Subcategory: {{service.subcategory.name}}</p>
{% endif %}

{% endfor %}
<a href="{% url 'services:service_form' %}">Create New Service</a>
<a href="{% url 'services:search' %}">Search For A Service</a>
<a href="{% url 'services:delete_service' service.id %}">Delete This Service</a>
{% if deleting_one_category %}
    <a href="{% url 'deleting_one_category' %}">Deleting</a>
{% endif %}



</body>
</html>

services/templates/update_service.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Update Service</button>
   <a href="{% url 'serviceform' %}">Back</a>
</form>
</body>
</html>